#!/bin/bash

tc="tc=0/30+0.3"

e1="-engine conf=coal $tc"
e2="-engine conf=cand $tc"

threads=6

m="-recover -concurrency $threads"

t="-event soaktest -tournament round-robin -games 20000"

r="-resign movecount=5 score=400"

d="-draw movenumber=40 movecount=8 score=10"

o="-repeat -srand $RANDOM -openings file=data/4moves_noob.epd format=epd order=random plies=16"

s="-sprt elo0=0 elo1=5 alpha=0.05 beta=0.05"

v="-ratinginterval 10"

f="-pgnout data/fens/$RAMDOM$RANDOM.pgn fi min"

echo $e1 $e2 $t $r $d $o $v $m $s $f

../cutechess-ob $e1 $e2 $t $r $d $o $v $m $s $1 $f | tee cutechess.log

