#!/bin/bash

coproc PROCESS { node ../../cwtch; }

while IFS= read -r line
do
  echo "label $line" >&${PROCESS[1]}
  read -r result <&${PROCESS[0]}
  echo "$result"
done < $1

echo "q" >&${PROCESS[1]}

exec 3>&${PROCESS[0]}- 4>&${PROCESS[1]}-
wait $PROCESS_PID
